services:
  - type: web
    name: puppeteer-scraper
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 8080
